-------------------------------------------------------------
--删除流程定义
--CHENYU 2010-10-28
-------------------------------------------------------------
Create Procedure SP_WorkflowItemDelete
	@WorkflowItemKey NVARCHAR(50)
AS	
	DELETE FROM FLW_LINK_CONDITIONS WHERE LINKID IN (SELECT ID FROM FLW_LINK WHERE FLOWINSTANCEID=@WorkflowItemKey)
	DELETE FROM FLW_LINK WHERE FLOWINSTANCEID=@WorkflowItemKey
	
	DELETE FROM FLW_NODE_ACTION WHERE NODEID IN (SELECT ID FROM FLW_NODE WHERE FLOWINSTANCEID=@WorkflowItemKey)
	DELETE FROM FLW_NODE_ORGANIZATION WHERE NODEID IN (SELECT ID FROM FLW_NODE WHERE FLOWINSTANCEID=@WorkflowItemKey)
	DELETE FROM FLW_NODE_PERMISSION WHERE NODEID IN (SELECT ID FROM FLW_NODE WHERE FLOWINSTANCEID=@WorkflowItemKey)
	DELETE FROM FLW_NODE_TIMEALARM WHERE NODEID IN (SELECT ID FROM FLW_NODE WHERE FLOWINSTANCEID=@WorkflowItemKey)
	DELETE FROM FLW_NODE_CCORGANIZATION WHERE NODEID IN (SELECT ID FROM FLW_NODE WHERE FLOWINSTANCEID=@WorkflowItemKey)
	DELETE FROM FLW_NODE WHERE FLOWINSTANCEID=@WorkflowItemKey
	
	DELETE FROM FLW_FORM WHERE FLOWID=@WorkflowItemKey
	
	DELETE FROM FLW_INSTANCE WHERE [ID]=@WorkflowItemKey

