ALTER  VIEW VIEW_WF_RECEIVEFILES
AS
SELECT  WF_USERTASK.EMPCODE, 
	WF_USERTASK.EMPNAME,
	WF_USERTASK.ID, 
      	WF_USERTASK.CREATETIME,
	 WF_USERTASK.VIEWTIME, 
	WF_TASK.CREATORNAME,
	 WF_TASK.ISEXIGENCE,
	WF_TASK.WF_INSTANCE_ID AS FLOWINSTID,
	(SELECT TOP 1 FLOWID FROM WF_INSTANCE  WHERE WF_INSTANCE.ID = WF_TASK.WF_INSTANCE_ID) AS FLOWID,
	(SELECT TOP 1 FLOWNAME  FROM WF_INSTANCE WHERE WF_INSTANCE.ID = WF_TASK.WF_INSTANCE_ID) AS FLOWNAME,
	(SELECT TOP 1 MAINFIELDVALUE FROM WF_INSTANCE WHERE WF_INSTANCE.ID = WF_TASK.WF_INSTANCE_ID) AS MAINFIELDVALUE,
 	(SELECT TOP 1  ISUSELESS FROM WF_INSTANCE WHERE WF_INSTANCE.ID = WF_TASK.WF_INSTANCE_ID) AS ISUSELESS,
	(SELECT TOP 1  TaskStatus FROM WF_INSTANCE WHERE WF_INSTANCE.ID = WF_TASK.WF_INSTANCE_ID) AS WorkflowInstState
FROM WF_USERTASK INNER JOIN WF_TASK ON WF_USERTASK.TASKID = WF_TASK.ID
WHERE (WF_USERTASK.TASKSTATUS = 1) 
--//OR (WF_USERTASK.TASKSTATUS = 2)

